//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WebViewViewController.h"

@class UIButton, UIScrollView;

@interface AdWebViewController : WebViewViewController
{
    UIScrollView *_scrollView;
    UIButton *_pasteButton;
}

@property(retain, nonatomic) UIButton *pasteButton; // @synthesize pasteButton=_pasteButton;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)pasteWeChat;
- (void)addHeadView;
- (void)viewDidLoad;

@end

