//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIApplicationDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITabBarControllerDelegate.h"

@class NSDictionary, NSString, UIWindow;

@interface AppDelegate : UIResponder <UIScrollViewDelegate, UITabBarControllerDelegate, UIApplicationDelegate>
{
    NSString *_requsetUrl;
    UIWindow *_window;
    NSDictionary *_userInfo;
}

+ (id)getDeviceId;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (id)createRequestUrl:(id)arg1;
- (void)requsetInit;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)registerUmengWithAppKey:(id)arg1;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (void)setTabbarController;
- (void)updateWhenLogout;
- (void)logout;
- (void)loginedWithUser:(id)arg1;
- (void)updateLogin:(id)arg1;
- (_Bool)isLogin;
- (_Bool)checkIsLogin;
- (void)presentLoginVC;
- (void)autoLogin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

