//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

@class UIButton, UITextField;

@interface ChangePwdViewController : RootViewController
{
    UITextField *_oldPwdTextField;
    UITextField *_pswTextField;
    UITextField *_confPswTextField;
    UIButton *_changeBtn;
}

@property(nonatomic) __weak UIButton *changeBtn; // @synthesize changeBtn=_changeBtn;
@property(nonatomic) __weak UITextField *confPswTextField; // @synthesize confPswTextField=_confPswTextField;
@property(nonatomic) __weak UITextField *pswTextField; // @synthesize pswTextField=_pswTextField;
@property(nonatomic) __weak UITextField *oldPwdTextField; // @synthesize oldPwdTextField=_oldPwdTextField;
- (void).cxx_destruct;
- (void)handelCommitChangePwd:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

