//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UIImageView, UILabel;

@interface ChannelCollectionViewCell : UICollectionViewCell
{
    UIImageView *_mainImageView;
    UILabel *_mainLabel;
    UIButton *_countButton;
}

@property(retain, nonatomic) UIButton *countButton; // @synthesize countButton=_countButton;
@property(retain, nonatomic) UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;
@property(retain, nonatomic) UIImageView *mainImageView; // @synthesize mainImageView=_mainImageView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

