//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

@class MyViewController, NSArray, NSString, UIAlertView, UIButton, UILabel, UIScrollView, UITextField;

@interface ChargeViewController : RootViewController
{
    NSString *_agentWechat;
    MyViewController *_myVC;
    UIScrollView *_backScrollView;
    UITextField *_carMTextField;
    UIAlertView *_av;
    NSArray *_cards;
    UILabel *_tipLabel;
    UIButton *_pasteButton;
}

@property(retain, nonatomic) UIButton *pasteButton; // @synthesize pasteButton=_pasteButton;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) NSArray *cards; // @synthesize cards=_cards;
@property(retain, nonatomic) UIAlertView *av; // @synthesize av=_av;
@property(retain, nonatomic) UITextField *carMTextField; // @synthesize carMTextField=_carMTextField;
@property(retain, nonatomic) UIScrollView *backScrollView; // @synthesize backScrollView=_backScrollView;
@property(nonatomic) MyViewController *myVC; // @synthesize myVC=_myVC;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)handleCarBuy:(id)arg1;
- (id)fetchCardInfo:(long long)arg1;
- (id)fetchUrlWith:(long long)arg1;
- (void)hendleReNew:(id)arg1;
- (void)fetchCards;
- (void)showAutoDismissAlert:(id)arg1;
- (void)dismissAlert;
- (void)delayToReLogin;
- (void)delayToBack;
- (void)delayToTip:(id)arg1;
- (void)refreshTipLabel;
- (id)chargeTipFormatAttributed;
- (void)pasteWeChat;
- (void)createUI;
- (void)viewDidLoad;

@end

