//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GTMBase : NSObject
{
}

+ (id)base64EncodedStringFrom:(id)arg1;
+ (id)dataWithBase64EncodedString:(id)arg1;
+ (id)DESDecrypt:(id)arg1 WithKey:(id)arg2;
+ (id)DESEncrypt:(id)arg1 WithKey:(id)arg2;
+ (id)textFromBase64String:(id)arg1;
+ (id)base64StringFromText:(id)arg1;

@end

