//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

#import "SDCycleScrollViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSDictionary, NSMutableArray, NSString, NSURLSessionDataTask, TXScrollLabelView, UIButton, UICollectionView, UILabel, UIScrollView;

@interface HomeViewController : RootViewController <UICollectionViewDelegate, UICollectionViewDataSource, SDCycleScrollViewDelegate, UIScrollViewDelegate>
{
    _Bool _canClick;
    NSString *_noticeString;
    UIScrollView *_contentView;
    UICollectionView *_collectionView;
    UICollectionView *_hotCollectionView;
    TXScrollLabelView *_scrollLabelView;
    UIButton *_hotTitleButton;
    UIButton *_listTitleButton;
    NSMutableArray *_mydataArray;
    NSMutableArray *_hotDataArray;
    NSDictionary *_vedioDictionary;
    NSURLSessionDataTask *_listTask;
    NSURLSessionDataTask *_hotTask;
    UILabel *_tipLabel;
}

@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) NSURLSessionDataTask *hotTask; // @synthesize hotTask=_hotTask;
@property(retain, nonatomic) NSURLSessionDataTask *listTask; // @synthesize listTask=_listTask;
@property(retain, nonatomic) NSDictionary *vedioDictionary; // @synthesize vedioDictionary=_vedioDictionary;
@property(retain, nonatomic) NSMutableArray *hotDataArray; // @synthesize hotDataArray=_hotDataArray;
@property(retain, nonatomic) NSMutableArray *mydataArray; // @synthesize mydataArray=_mydataArray;
@property(retain, nonatomic) UIButton *listTitleButton; // @synthesize listTitleButton=_listTitleButton;
@property(retain, nonatomic) UIButton *hotTitleButton; // @synthesize hotTitleButton=_hotTitleButton;
@property(retain, nonatomic) TXScrollLabelView *scrollLabelView; // @synthesize scrollLabelView=_scrollLabelView;
@property(retain, nonatomic) UICollectionView *hotCollectionView; // @synthesize hotCollectionView=_hotCollectionView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) NSString *noticeString; // @synthesize noticeString=_noticeString;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (struct CGSize)GetStringProperSize:(id)arg1 font:(id)arg2;
- (id)selectVedioUrlDictionary;
- (id)adsURLs;
- (void)cycleScrollView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)createHomeUI;
- (void)addRefreshHeader2;
- (void)addRefreshHeader;
- (void)requestListForHome;
- (void)requestForHot;
- (void)fetchAd;
- (void)changeInfoView;
- (void)startRequest2;
- (void)startRequest;
- (void)refreshHomeData;
- (void)clickListTitleButton:(id)arg1;
- (void)clickHotTitleButton:(id)arg1;
- (void)addNotification;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupTitleView;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

