//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface HotCollectionViewCell : UICollectionViewCell
{
    UIImageView *_mainImageView;
    UILabel *_leftLabel;
    UIImageView *_iconView;
    UIView *_countBackView;
    UIButton *_peopleCountButton;
}

@property(retain, nonatomic) UIButton *peopleCountButton; // @synthesize peopleCountButton=_peopleCountButton;
@property(retain, nonatomic) UIView *countBackView; // @synthesize countBackView=_countBackView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(retain, nonatomic) UIImageView *mainImageView; // @synthesize mainImageView=_mainImageView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

