//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class NSDictionary, UIButton, UIImageView, UILabel, UIView;

@interface HouseHeadCollectionReusableView : UICollectionReusableView
{
    UIImageView *_backView;
    UIImageView *_iconView;
    UILabel *_titleLabel;
    UIButton *_countButton;
    UIView *_lineView;
    UILabel *_detailLabel;
    NSDictionary *_data;
}

@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIButton *countButton; // @synthesize countButton=_countButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIImageView *backView; // @synthesize backView=_backView;
- (void).cxx_destruct;
- (struct CGSize)GetStringProperSize:(id)arg1 font:(id)arg2;
- (void)setupDetailLabel;
- (void)setupLineView;
- (void)setupCountButton;
- (void)setupTitleLabel;
- (void)setupIconView;
- (void)setupBackView;
- (void)fillContentView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

