//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMutableArray, NSString, NSURLSessionDataTask, UICollectionView;

@interface HouseListViewController : RootViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
    _Bool _hiddenStatusBar;
    _Bool _canClick;
    NSString *_liveId;
    NSString *_appImg;
    UICollectionView *_collectionView;
    NSMutableArray *_mydataArray;
    NSURLSessionDataTask *_listTask;
}

@property(retain, nonatomic) NSURLSessionDataTask *listTask; // @synthesize listTask=_listTask;
@property(retain, nonatomic) NSMutableArray *mydataArray; // @synthesize mydataArray=_mydataArray;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain) NSString *appImg; // @synthesize appImg=_appImg;
@property(retain) NSString *liveId; // @synthesize liveId=_liveId;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (struct CGSize)GetStringProperSize:(id)arg1 font:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)createHomeSecondUI;
- (void)addRefreshHeader;
- (void)requestListForHouse;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

