//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView;

@interface IZCActivityIndicatorView : UIView
{
    _Bool _animating;
    UIView *_grayBgView;
    double _angle;
    UIActivityIndicatorView *_loadingView;
}

@property(retain, nonatomic) UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) double angle; // @synthesize angle=_angle;
@property(retain, nonatomic) UIView *grayBgView; // @synthesize grayBgView=_grayBgView;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
- (void).cxx_destruct;
- (_Bool)isAnimating;
- (void)stopAnimating;
- (void)startAnimating;
- (void)layoutSubviews;
- (id)init;
- (void)dealloc;

@end

