//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "WKNavigationDelegate.h"
#import "WKUIDelegate.h"

@class NSString, UIBarButtonItem, UIColor, UIProgressView, WKWebView;

@interface KINWebBrowserViewController : UIViewController <WKNavigationDelegate, WKUIDelegate>
{
    _Bool _showsURLInNavigationBar;
    _Bool _showsPageTitleInNavigationBar;
    _Bool _previousNavigationControllerToolbarHidden;
    _Bool _previousNavigationControllerNavigationBarHidden;
    id <KINWebBrowserDelegate> _delegate;
    UIColor *_tintColor;
    UIColor *_barTintColor;
    UIProgressView *_progressView;
    WKWebView *_wkWebView;
    UIBarButtonItem *_backButton;
    UIBarButtonItem *_forwardButton;
    UIBarButtonItem *_refreshButton;
    UIBarButtonItem *_stopButton;
    UIBarButtonItem *_fixedSeparator;
    UIBarButtonItem *_flexibleSeparator;
}

+ (id)navigationControllerWithBrowser:(id)arg1;
+ (id)navigationControllerWithWebBrowserWithConfiguration:(id)arg1;
+ (id)navigationControllerWithWebBrowser;
+ (id)webBrowserWithConfiguration:(id)arg1;
+ (id)webBrowser;
@property(retain, nonatomic) UIBarButtonItem *flexibleSeparator; // @synthesize flexibleSeparator=_flexibleSeparator;
@property(retain, nonatomic) UIBarButtonItem *fixedSeparator; // @synthesize fixedSeparator=_fixedSeparator;
@property(retain, nonatomic) UIBarButtonItem *stopButton; // @synthesize stopButton=_stopButton;
@property(retain, nonatomic) UIBarButtonItem *refreshButton; // @synthesize refreshButton=_refreshButton;
@property(retain, nonatomic) UIBarButtonItem *forwardButton; // @synthesize forwardButton=_forwardButton;
@property(retain, nonatomic) UIBarButtonItem *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) _Bool previousNavigationControllerNavigationBarHidden; // @synthesize previousNavigationControllerNavigationBarHidden=_previousNavigationControllerNavigationBarHidden;
@property(nonatomic) _Bool previousNavigationControllerToolbarHidden; // @synthesize previousNavigationControllerToolbarHidden=_previousNavigationControllerToolbarHidden;
@property(retain, nonatomic) WKWebView *wkWebView; // @synthesize wkWebView=_wkWebView;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) _Bool showsPageTitleInNavigationBar; // @synthesize showsPageTitleInNavigationBar=_showsPageTitleInNavigationBar;
@property(nonatomic) _Bool showsURLInNavigationBar; // @synthesize showsURLInNavigationBar=_showsURLInNavigationBar;
@property(retain, nonatomic) UIColor *barTintColor; // @synthesize barTintColor=_barTintColor;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(nonatomic) __weak id <KINWebBrowserDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)validateHttpOrHttps:(id)arg1;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dismissAnimated:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)stopButtonPressed:(id)arg1;
- (void)refreshButtonPressed:(id)arg1;
- (void)forwardButtonPressed:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)doneButtonPressed:(id)arg1;
- (void)setupToolbarItems;
- (void)updateToolbarState;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)loadURLString:(id)arg1;
- (void)loadURL:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithConfiguration:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

