//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

#import "RegisterAViewControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, UIButton, UITextField;

@interface LoginViewController : RootViewController <RegisterAViewControllerDelegate, UITextFieldDelegate>
{
    UITextField *_userNameTextField;
    UITextField *_pswTextField;
    UIButton *_loginBtn;
    UIButton *_regBtn;
}

@property(nonatomic) __weak UIButton *regBtn; // @synthesize regBtn=_regBtn;
@property(nonatomic) __weak UIButton *loginBtn; // @synthesize loginBtn=_loginBtn;
@property(nonatomic) __weak UITextField *pswTextField; // @synthesize pswTextField=_pswTextField;
@property(nonatomic) __weak UITextField *userNameTextField; // @synthesize userNameTextField=_userNameTextField;
- (void).cxx_destruct;
- (void)successRegister:(id)arg1 andPassword:(id)arg2;
- (void)handletoRegister:(id)arg1;
- (void)handleTapToLogin:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)dissmis;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

