//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

#import "LiverViewControllerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMutableArray, NSString, NSURLSessionDataTask, UICollectionView;

@interface MyFavoriteViewController : RootViewController <UICollectionViewDataSource, UICollectionViewDelegate, LiverViewControllerDelegate>
{
    long long _selectItem;
    _Bool _hiddenStatusBar;
    _Bool _isNeedRefresh;
    _Bool _canClick;
    UICollectionView *_collectionView;
    NSMutableArray *_mydataArray;
    NSURLSessionDataTask *_listTask;
}

@property(retain, nonatomic) NSURLSessionDataTask *listTask; // @synthesize listTask=_listTask;
@property(retain, nonatomic) NSMutableArray *mydataArray; // @synthesize mydataArray=_mydataArray;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (struct CGSize)GetStringProperSize:(id)arg1 font:(id)arg2;
- (void)successCollectionAction:(_Bool)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)longpress:(id)arg1;
- (void)changeCollection:(_Bool)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)createHomeSecondUI;
- (void)addRefreshHeader;
- (void)requestListForMyFavorite;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

