//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface MyViewController : RootViewController <UITableViewDataSource, UITableViewDelegate>
{
    long long _barStyle;
    UITableView *_myTableView;
    NSMutableArray *_mydataArray;
}

@property(retain, nonatomic) NSMutableArray *mydataArray; // @synthesize mydataArray=_mydataArray;
@property(retain, nonatomic) UITableView *myTableView; // @synthesize myTableView=_myTableView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (long long)preferredStatusBarStyle;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)createUI;
- (void)handleLogout:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

