//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTimer.h"

@interface NSTimer (TXTimerTarget)
+ (void)startTimer:(id)arg1;
+ (id)tx_scheduledTimerWithTimeInterval:(double)arg1 repeat:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
@end

