//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

@class UIButton, UITextField;

@interface RegisterAViewController : RootViewController
{
    UITextField *_userNameTextField;
    UITextField *_pswTextField;
    UITextField *_confPswTextField;
    UITextField *_promoCodeTextField;
    UIButton *_toRegBtn;
    id <RegisterAViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <RegisterAViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIButton *toRegBtn; // @synthesize toRegBtn=_toRegBtn;
@property(nonatomic) __weak UITextField *promoCodeTextField; // @synthesize promoCodeTextField=_promoCodeTextField;
@property(nonatomic) __weak UITextField *confPswTextField; // @synthesize confPswTextField=_confPswTextField;
@property(nonatomic) __weak UITextField *pswTextField; // @synthesize pswTextField=_pswTextField;
@property(nonatomic) __weak UITextField *userNameTextField; // @synthesize userNameTextField=_userNameTextField;
- (void).cxx_destruct;
- (void)handletoCommitRegister:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

