//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class UILabel;

@interface TVBroadcastCollectionReusableView : UICollectionReusableView
{
    UILabel *_countLabel;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
- (void).cxx_destruct;
- (void)setupDetailLabel;
- (void)setupTitleLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

