//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (TXFrame)
@property(nonatomic) double tx_bottom;
@property(nonatomic) double tx_centerY;
@property(nonatomic) double tx_centerX;
@property(nonatomic) struct CGPoint tx_center;
@property(nonatomic) struct CGPoint tx_origin;
@property(nonatomic) struct CGSize tx_size;
@property(nonatomic) double tx_height;
@property(nonatomic) double tx_width;
@property(nonatomic) double tx_y;
@property(nonatomic) double tx_x;
@end

