//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RootViewController.h"

#import "SDCycleScrollViewDelegate.h"

@class NSDictionary, NSString, SDCycleScrollView, UIScrollView;

@interface VideoHomeViewController : RootViewController <SDCycleScrollViewDelegate>
{
    long long _barStyle;
    UIScrollView *_scrollView;
    SDCycleScrollView *_sdScrollView;
    NSDictionary *_vedioDictionary;
}

@property(retain, nonatomic) NSDictionary *vedioDictionary; // @synthesize vedioDictionary=_vedioDictionary;
@property(retain, nonatomic) SDCycleScrollView *sdScrollView; // @synthesize sdScrollView=_sdScrollView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (long long)preferredStatusBarStyle;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupSubviews;
- (void)setupScrollView;
- (void)cycleScrollView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)adsLoadSuccess:(id)arg1;
- (void)play:(id)arg1 andTitle:(id)arg2;
- (void)platformPlay:(id)arg1;
- (void)TVBroadcastPlay;
- (void)vipVedioPlay;
- (void)errorWithAddressUnExist;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

