//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KINWebBrowserViewController.h"

@class NSString, UIButton;

@interface VideoPageWebViewController : KINWebBrowserViewController
{
    NSString *_clickURL;
    _Bool _addPlayButton;
    UIButton *_playButton;
}

@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(nonatomic) _Bool addPlayButton; // @synthesize addPlayButton=_addPlayButton;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)playVedio;
- (void)viewDidLoad;

@end

