//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZQBasicAPI : NSObject
{
}

+ (_Bool)isEmailAddress:(id)arg1;
+ (_Bool)validateIdentityCard:(id)arg1;
+ (_Bool)verifyPassword:(id)arg1;
+ (_Bool)verifyPhoneNumber:(id)arg1;
+ (_Bool)judgeUserIsLogin;
+ (_Bool)isValidateByRegex:(id)arg1;

@end

