//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPSessionManager;

@interface ZQNetWorkingTool : NSObject
{
    AFHTTPSessionManager *_manager;
}

+ (id)jsonStringFromData:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) AFHTTPSessionManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (id)postWithUrl:(id)arg1 param:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)setupHTTPSessionManager;
- (id)init;

@end

